### PR TITLE
Fix: Alias renamed dependencies in generated build rules.

### LINKED ISSUE #143: Actix-web failed with: failed to resolve: use of undeclared type or module `fail_ure`
Hi, I'm trying to compile the following actix-web example in my Bazel project: https://github.com/actix/examples/tree/master/multipart
and I have ended up with the following error:

```
error[E0433]: failed to resolve: use of undeclared type or module `fail_ure`
   --> third_party/cargo/vendor/actix-http-1.0.1/src/error.rs:968:24
    |
968 | impl ResponseError for fail_ure::Error {}
    |                        ^^^^^^^^ use of undeclared type or module `fail_ure`

error: aborting due to previous error
```
The same code perfectly compiles using cargo...

Any ideas how to fix it?

### PR DESCRIPTION
**Pull request by Arm1stice**
This PR fixes #143 by checking for renamed packages while exploring dependencies. If a package has been renamed, it will be added to the `aliases` parameter in the generated build rule.

I am still fairly new to Rust programming and it's best practices, so please feel free to nit my implementation.

Once you approve of the implementation, I can write unit tests before merging.

### CODE REVIEW

**Comment by dfreese** [comment]
Sounds fairly similar to #123.  I think that approach was okay, but he wanted to add further tests.  My reading of that thread was that approach was alright, if you want to compare.

File: impl/src/planning.rs [hunk 1]
```diff
@@ -624,12 +653,22 @@ impl<'planner> CrateSubplanner<'planner> {
           )
         }
       }
+
+      // Check if the dependency has been renamed
+      if dep.rename.is_some() {
```
Comment (smklein) [inline impl/src/planning.rs:658]: Might be more canonical to use:

```
dep.rename.map(|rename| {
  renamed_dep_names.insert(
    dep.name.clone(),
    format!("{}", rename),
  );
})
```

As this would avoid the unwrap

File: impl/src/planning.rs [hunk 2]
```diff
@@ -572,6 +588,15 @@ impl<'planner> CrateSubplanner<'planner> {
 
       if normal_dep_names.contains(&dep_package.name) {
         normal_deps.push(buildable_dependency);
+        // Only add renamed normal deps to the HashMap
+        let package_alias = renamed_dep_names.get(&dep_package.name);
+        if package_alias.is_some() {
```
Comment (smklein) [inline impl/src/planning.rs:593]: Same as comment below; a `map` might help avoid the unwrap.

File: impl/src/planning.rs (hunk 1 above)
Comment (Arm1stice) [reply impl/src/planning.rs]: Thank you for this! Looks like I had to add `.as_ref()` before `.map` to appease rustc.

File: impl/src/planning.rs [hunk 3]
```diff
@@ -624,12 +652,21 @@ impl<'planner> CrateSubplanner<'planner> {
           )
         }
       }
+
+      // Check if the dependency has been renamed
+      dep.rename.as_ref().map(|rename| {
```
Comment (dfreese) [inline impl/src/planning.rs:657]: Talked with @smklein about this a little later, so sorry for asking to change this again, but rust also has a [`if let`](https://doc.rust-lang.org/stable/rust-by-example/flow_control/if_let.html) pattern matching syntax.  That would probably be the clearest here.

```
if let Some(alias) = dep.rename.as_ref() {
  // everything in the closure
}
```

File: impl/src/planning.rs [hunk 4]
```diff
@@ -624,12 +652,21 @@ impl<'planner> CrateSubplanner<'planner> {
...
+        renamed_dep_names.insert(
+          dep.name.clone(),
+          format!("{}", rename),
```
Comment (dfreese) [inline impl/src/planning.rs:660]: can this format be shortened to rename.clone()?

File: impl/src/planning.rs [hunk 5]
```diff
@@ -486,6 +491,13 @@ impl<'planner> CrateSubplanner<'planner> {
         }
       }
     }
+
+    // Take the hashmap and create a vector of strings that will be inserted into the template.
+    let mut aliased_dependencies = Vec::new();
+    for (name, alias) in &renamed_deps {
+      aliased_dependencies.push(format!("\"{}\": \"{}\",", name.clone(), alias.clone()));
```
Comment (dfreese) [inline impl/src/planning.rs:498]: Are the clone() calls needed here, or could the variables be borrowed?  &name, &alias

File: impl/src/planning.rs [hunk 6]
```diff
@@ -63,6 +63,8 @@ struct DependencyNames {
   build_dep_names: Vec<String>,
   // Dependencies that are required for tests
   dev_dep_names: Vec<String>,
+  // Dependencies that have been renamed
+  renamed_dep_names: HashMap<String, String>,
```
Comment (dfreese) [inline impl/src/planning.rs:67]: could this be called `aliased_dep_names`, and then `aliased_deps` line 80?

I think that will make it a little more clear that aliases are being used the entire time.

File: impl/src/planning.rs [hunk 7]
```diff
@@ -74,6 +76,8 @@ struct DependencySet {
   build_deps: Vec<BuildableDependency>,
   // Dependencies that are required for tests
   dev_deps: Vec<BuildableDependency>,
+  // Dependencies that have been renamed and need to be aliased in the build rule
+  renamed_deps: HashMap<String, String>,
```
Comment (dfreese) [inline impl/src/planning.rs:80]: It doesn't look like you use the lookup into this hashmap.  Could this, instead, be a Vec of a struct, similar to [DependencyAlias](https://github.com/google/cargo-raze/pull/123/commits/fde76fdffe5fc645a41c4615486191b3330da27a#diff-b839b62c6331bbd8524ee98a856d496eR57-R61) here?

File: impl/src/planning.rs [hunk 8]
```diff
@@ -572,6 +588,14 @@ impl<'planner> CrateSubplanner<'planner> {
 
       if normal_dep_names.contains(&dep_package.name) {
         normal_deps.push(buildable_dependency);
+        // Only add renamed normal deps to the HashMap
+        let package_alias = renamed_dep_names.get(&dep_package.name);
+        package_alias.as_ref().map(|alias| {
+          renamed_deps.insert(
+            buildable_target.clone(),
+            alias.replace("-", "_"),
```
[the remark this answers is not in the document]
Comment (dfreese) [reply impl/src/planning.rs:596]: (Doing this replace could also probably be saved until the last `format!(..., util::sanitize_name(alias))` you make to build up the `aliased_dependencies` vector.

File: impl/src/planning.rs (hunk 4 above)
Comment (Arm1stice) [reply impl/src/planning.rs:660]: It was giving me compiler errors before for some reason, but now that we switched to the `if let` syntax I'll change it.

File: impl/src/planning.rs (hunk 3 above)
Comment (Arm1stice) [reply impl/src/planning.rs:657]: Sounds good. Changed to `if let`

File: impl/src/planning.rs (hunk 6 above)
Comment (Arm1stice) [reply impl/src/planning.rs:67]: Changed the names.

File: impl/src/planning.rs (hunk 7 above)
Comment (Arm1stice) [reply impl/src/planning.rs:80]: I went ahead and changed it to a Vec<String>. Because of this, I moved the logic that creates the alias strings for the template into `produce_deps`

File: impl/src/planning.rs (hunk 5 above)
Comment (Arm1stice) [reply impl/src/planning.rs:498]: This logic no longer lives in this function and now doesn't involve looping through a HashMap. Resolving.

File: impl/src/planning.rs [hunk 9]
```diff
@@ -486,6 +491,13 @@ impl<'planner> CrateSubplanner<'planner> {
         }
       }
     }
+
+    // Take the hashmap and create a vector of strings that will be inserted into the template.
+    let mut aliased_dependencies = Vec::new();
```
[the remark this answers is not in the document]
Comment (Arm1stice) [reply impl/src/planning.rs:496]: This logic has been reworked to avoid looping through a HashMap. Resolving.

File: impl/src/planning.rs (hunk 8 above)
[the remark this answers is not in the document]
Comment (Arm1stice) [reply impl/src/planning.rs:596]: Went ahead and created `sanitize_name`. For your last comment, I moved the logic to call the function when producing the Vec<String> in `produce_deps`

File: impl/src/planning.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (Arm1stice) [reply impl/src/planning.rs]: This has been renamed to `aliased` in the latest commit (I pushed about 30 seconds after your comments popped up) per https://github.com/google/cargo-raze/pull/162#discussion_r433554446. In the HashMap the key is the label of Bazel target, and the value is the name it is being aliased to in the `rust_library`/`rust_binary` rule.

File: impl/src/planning.rs [hunk 10]
```diff
@@ -593,6 +618,9 @@ impl<'planner> CrateSubplanner<'planner> {
     let mut dev_dep_names = Vec::new();
     let mut normal_dep_names = Vec::new();
 
+    // Store renamed dependencies in a HashMap
+    let mut renamed_dep_names = HashMap::new();
```
[the remark this answers is not in the document]
Comment (Arm1stice) [reply impl/src/planning.rs]: The variable is defined here because the usage is at the bottom of the `for` loop.

**Comment by Arm1stice** [comment]
I made changes based on @dfreese's comments, and responded to @acmcarther's comments

File: impl/src/planning.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (acmcarther) [reply impl/src/planning.rs]: (My suggestion here is to move this declaration to L656)

File: impl/src/planning.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (acmcarther) [reply impl/src/planning.rs]: This needs to be pushed I think

[the remark this answers is not in the document]
Comment (Arm1stice) [reply impl/src/planning.rs]: https://github.com/google/cargo-raze/pull/162/commits/993622e766ccad5f6693ef1e2ad2e414b80a7a11

[the remark this answers is not in the document]
Comment (acmcarther) [reply impl/src/planning.rs]: Sorry, I think I was confused by the github UI. Thanks for clarifying, marking resulved.

File: impl/src/planning.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (Arm1stice) [reply impl/src/planning.rs]: [L656 in the commit this review is based on](https://github.com/google/cargo-raze/blob/5708a78840fd58389278de6c2695a9002a2bb9b8/impl/src/planning.rs#L656) is inside of the `for` loop. The logic looks weird, but that `map` (which has now been changed to `if let` syntax) was only to avoid unwrapping `dep.rename`. The HashMap needs to be declared above the `for` loop so that any renamed dependencies can be added to it. [The latest commit](https://github.com/google/cargo-raze/blob/993622e766ccad5f6693ef1e2ad2e414b80a7a11/impl/src/planning.rs#L612-L650) makes this logic much more readable.

[the remark this answers is not in the document]
Comment (acmcarther) [reply impl/src/planning.rs]: My bad, you're definitely right. Another useless comment from me, hah.

Marking resolved.

File: impl/src/planning.rs [hunk 11]
```diff
@@ -74,6 +76,8 @@ struct DependencySet {
   build_deps: Vec<BuildableDependency>,
   // Dependencies that are required for tests
   dev_deps: Vec<BuildableDependency>,
+  // Dependencies that have been renamed and need to be aliased in the build rule
```
Comment (acmcarther) [inline impl/src/planning.rs:79]: Optional: This appears to contain strings of keys and values. This isn't obvious from the type Consider adding a note, like

```
  // Dependencies that have been renamed and need to be aliased in the build rule
  // formatted as `"$TARGET_NAME": "$BUILD_ALIAS"`
```

A slightly more type safe way to do this would be to use a simple struct containing these values, and do this formatting "later", but I don't feel strongly enough about this to really suggest it here.

File: impl/src/util.rs [hunk 12]
```diff
@@ -163,6 +163,10 @@ pub fn sanitize_ident(ident: &str) -> String {
   slug::slugify(&ident).replace("-", "_")
 }
 
+pub fn sanitize_name(name: &str) -> String {
```
Comment (acmcarther) [inline impl/src/util.rs:166]: This is identical to sanitize_ident. Can that be used instead?

Comment (Arm1stice) [reply impl/src/util.rs:166]: This was made due to the suggestion at https://github.com/google/cargo-raze/pull/162#discussion_r433539678

File: impl/src/planning.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (Arm1stice) [reply impl/src/planning.rs]: No worries!

File: impl/src/planning.rs (hunk 11 above)
Comment (Arm1stice) [reply impl/src/planning.rs:79]: Just pushed a new commit pulling this out to a simple struct. Let me know what you think.

File: impl/src/util.rs (hunk 12 above)
Comment (acmcarther) [reply impl/src/util.rs:166]: I guess lets hear if @dfreese intended to have a function with a different name but the same implementation. I think he expected that sanitize_name would just contain the "-" -> "_", but it ended up containing the "slugify" as well.

File: impl/src/templates/partials/rust_binary.template [hunk 13]
```diff
@@ -36,4 +36,11 @@ rust_binary(
         "{{feature}}",
         {%- endfor %}
     ],
+    {%- if crate.aliased_dependencies | length != 0 %}
+    aliases = {
+        {%- for alias in crate.aliased_dependencies %}
+        {{alias}}
```
Comment (acmcarther) [inline impl/src/templates/partials/rust_binary.template:42]: Does this need to be fixed to match rust_library.template?

File: impl/src/planning.rs (hunk 11 above)
Comment (acmcarther) [reply impl/src/planning.rs:79]: This looks good to me, thanks for making this change. Marking resolved.

File: impl/src/util.rs (hunk 12 above)
Comment (dfreese) [reply impl/src/util.rs:166]: The intention was for it to just be `name.replace("-", "_")`

Comment (dfreese) [reply impl/src/util.rs:166]: Though, it was in part because I wasn't completely familiar with slugify.  I guess it could work to just use the `sanitize_ident` function in all cases.  @acmcarther do you have a preference on that?

File: impl/src/templates/partials/rust_binary.template (hunk 13 above)
Comment (Arm1stice) [reply impl/src/templates/partials/rust_binary.template]: Good catch, thank you

File: impl/src/util.rs (hunk 12 above)
Comment (Arm1stice) [reply impl/src/util.rs]: Ah I see. For now, I have removed `sanitize_name` and changed it to call `sanitize_ident`. I can change it further if needed.

**Comment by acmcarther** [comment]
I see the build in https://travis-ci.org/github/google/cargo-raze/builds/694036367 but it's not showing up here. Investigating this now.

I would second the request for a unit test as well.

**Comment by Arm1stice** [comment]
I agree with writing unit tests. I'll try to get them done by EOW

**Comment by Arm1stice** [comment]
Added a unit test based on the issue that this PR fixes. Let me know if it looks alright.

**Comment by dfreese** [comment]
Sweet!  Looks great!  Minor nit: looks like `cargo fmt` needs be run in `impl`, otherwise good to me.

**Comment by Arm1stice** [comment]
Okay, just pushed the new commit with `cargo fmt`

**Comment by dfreese** [comment]
Thanks!  LGTM

**Comment by Arm1stice** [comment]
Awesome! Thank you again for all of the comments.
